src/Http/routes.php
<?php

Route::resource('roles', 'RolesController');
Route::resource('permissions', 'PermissionsController');
Route::resource('users.roles', 'UsersRolesController', ['only' => ['index', 'create', 'store']]);

Route::put('users/{user}/roles', ['as' => 'users.roles.update', 'uses' => 'UsersRolesController@update']);
Route::put('users/{user}/update-organization-roles', ['as' => 'users.roles.update-organization-roles', 'uses' => 'UsersRolesController@updateOrganizationRoles']);
Route::put('users/{user}/update-generic-roles', ['as' => 'users.roles.update-generic-roles', 'uses' => 'UsersRolesController@updateGenericRoles']);

src/Models/Permission.php
<?php

namespace Klopal\Permissions\Models;

use Illuminate\Database\Eloquent\Model;
use Klopal\Permissions\Exceptions\PermissionDoesNotExist;
use Klopal\Permissions\Models\Traits\RefreshesPermissionCache;
use Klopal\Permissions\Contracts\Permission as PermissionContract;

class Permission extends Model implements PermissionContract
{
    // When ever permission is stored, updated, deleted we flush related cache.
    use RefreshesPermissionCache;

    /**
     * The attributes that aren't mass assignable.
     *
     * @var array
     */
    public $fillable = ['name', 'description'];

    /**
     * Create a new Eloquent model instance.
     *
     * @param array $attributes
     */
    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);

        $this->setTable(config('klopal-permissions.table_names.permissions'));
    }

    /**
     * A permission can be applied to roles.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function roles()
    {
        return $this->belongsToMany(
            config('klopal-permissions.models.role'),
            config('klopal-permissions.table_names.permission_role')
        )->withTimestamps();
    }

    /**
     * Find a permission by its name.
     *
     * @param string $name
     * @return mixed
     * @throws PermissionDoesNotExist
     */
    public static function findByName($name)
    {
        $permission = static::where('name', $name)->first();

        if (!$permission) {
            throw PermissionDoesNotExist::doesNotExist($name);
        }

        return $permission;
    }
}

src/Http/Controllers/Traits/Permissions.php
<?php

namespace Klopal\Permissions\Http\Controllers\Traits;

use Illuminate\Http\Request;
use Illuminate\Routing\Router;
use Klopal\Permissions\Routes;
use Klopal\Permissions\Contracts\Permission;

trait Permissions
{
    /**
     * @param Request $request
     * @param Router $router
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(Request $request, Router $router, Routes $routes)
    {
        abort_unless($request->user()->can($router->currentRouteName()), 403);

        $permissions = app(Permission::class)->all();

        $routes = $routes->virtualPermissionRoutes($permissions);

        return view('permissions::permissions.index', compact('permissions', 'routes'));
    }

    /**
     * @param Request $request
     * @param Router $router
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create(Request $request, Router $router)
    {
        abort_unless($request->user()->can($router->currentRouteName()), 403);

        $permission = app(Permission::class);

        return view('permissions::permissions.create', compact('permission'));
    }

    /**
     * @param Request $request
     * @param Router $router
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request, Router $router)
    {
        abort_unless($request->user()->can($router->currentRouteName()), 403);

        $existingRoutes = collect($router->getRoutes())->map(function ($route) {
            return $route->getName();
        })->implode(',');

        // Given name can not been found in database neither from routes.
        $this->validate($request, [
            'name' => 'required|max:255|unique:permissions,name|not_in:'. $existingRoutes,
        ],[
            'not_in' => trans('permissions::validation.exist_in_routes'),
        ]);

        app(Permission::class)->create($request->all());

        return redirect()->route('permissions.index');
    }

    /**
     * @param Request $request
     * @param Router $router
     * @param $permission
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show(Request $request, Router $router, $permission)
    {
        abort_unless($request->user()->can($router->currentRouteName()), 403);

        $permission = app(Permission::class)->findOrFail($permission);

        return view('permissions::permissions.show', compact('permission'));
    }

    /**
     * @param Request $request
     * @param Router $router
     * @param Permission $permission
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(Request $request, Router $router, $permission)
    {
        abort_unless($request->user()->can($router->currentRouteName()), 403);

        $permission = app(Permission::class)->findOrFail($permission);

        return view('permissions::permissions.edit', compact('permission'));
    }

    /**
     * @param Request $request
     * @param Router $router
     * @param $permission
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, Router $router, $permission)
    {
        abort_unless($request->user()->can($router->currentRouteName()), 403);

        $permission = app(Permission::class)->findOrFail($permission);

        $this->validate($request, [
            'name' => 'required|max:255|unique:permissions,name,' . $permission->id,
        ]);

        $permission->update($request->all());

        return redirect()->route('permissions.index');
    }

    /**
     * @param Request $request
     * @param Router $router
     * @param $permission
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(Request $request, Router $router, $permission)
    {
        abort_unless($request->user()->can($router->currentRouteName()), 403);

        $permission = app(Permission::class)->findOrFail($permission);

        $permission->delete();

        return redirect()->route('permissions.index');
    }
}

src/resources/views/permissions/partials/form.blade.php
<form method="POST"
      action="{{ $permission->exists ? route('permissions.update', $permission) : route('permissions.store') }}"
      accept-charset="UTF-8">
    @if($permission->exists)<input name="_method" type="hidden" value="PUT">@endif
    <input name="_token" type="hidden" value="{{ csrf_token() }}">

    <div class="form-group{{ $errors->first('name', ' has-error') }}">
        <label for="name" class="control-label">@lang('permissions::permissions.name')</label>
        <input class="form-control" name="name" type="text" id="name" value="{{ old('name', $permission->name) }}">
        <span class="help-block">{{ $errors->first('name', ':message') }}</span>
        @if(!$errors->first('name'))<span class="help-block"></span>@endif
    </div>

    <div class="form-group{{ $errors->first('description', ' has-error') }}">
        <label for="description" class="control-label">@lang('permissions::permissions.description')</label>
        <textarea class="form-control" name="description" cols="50" rows="5"
                  id="description">{{ old('description', $permission->description) }}</textarea>
        <span class="help-block">{{ $errors->first('description', ':message') }}</span>
    </div>

    <hr/>

    <button class="btn btn-w-m btn-primary" type="submit"><i
                class="fa fa-fw fa-check"></i>@lang('permissions::permissions.save')</button>
</form>

src/resources/views/permissions/partials/index.blade.php
<table class="table table-bordered">
    <tr>
        <td class="col-sm-3">@lang('permissions::permissions.permissions_count')</td>
        <td class="col-sm-3">{{ count($permissions) }}</td>
        <td class="col-sm-3">@lang('permissions::permissions.routes_count')</td>
        <td class="col-sm-3">{{ count($routes) }}</td>
    </tr>
</table>

<hr />

<table class="table table-condensed table-hover">
    <thead>
    <th class="col-sm-3">@lang('permissions::permissions.name')</th>
    <th class="col-sm-7">@lang('permissions::permissions.description')</th>
    <th class="col-sm-2"></th>
    </thead>
    <tbody>
    @foreach ($permissions as $permission)
        <tr>
            <td>{{ $permission->name }}</td>
            <td>{{ $permission->description }}</td>
            <td class="text-right">
                <a class="btn btn-sm btn-default"
                   href="{{ route('permissions.show', $permission) }}">
                    <i class="fa fa-search" aria-hidden="true"></i>
                </a>
        </tr>
    @endforeach
    @foreach ($routes as $route)
        @if(!empty($route))
            <tr>
                <td>{{ $route }}</td>
                <td></td>
                <td class="text-right">
                    <button class="btn btn-sm btn-default" href="#" disabled>
                        @lang('permissions::permissions.virtual_permission')
                    </button></td>
            </tr>
        @endif
    @endforeach
    </tbody>
</table>

src/resources/views/permissions/partials/show.blade.php
<div class="row">
    <div class="col-sm-4 col-md-2">
        @lang('permissions.name')
    </div>
    <div class="col-sm-8 col-md-10">
        {{ $permission->name }}
    </div>
</div>

@hr

<div class="row">
    <div class="col-sm-4 col-md-2">
        @lang('permissions.description')
    </div>
    <div class="col-sm-8 col-md-10">
        {{ $permission->description }}
    </div>
</div>

@hr

<div class="row">
    <div class="col-sm-4 col-md-2">
        @lang('permissions.related_roles')
    </div>
    <div class="col-sm-8 col-md-10">

        @forelse($permission->roles as $role)
            {{ $role->slug }}@if($loop->remaining), @endif
        @empty

        @endforelse
    </div>
</div>

@hr

<div class="row">
    <div class="col-sm-4 col-md-2">
        @lang('common.created_at')
    </div>
    <div class="col-sm-8 col-md-10">
        {{ $permission->created_at }}
    </div>
</div>

@hr

<div class="row">
    <div class="col-sm-4 col-md-2">
        @lang('common.updated_at')
    </div>
    <div class="col-sm-8 col-md-10">
        {{ $permission->updated_at }}
    </div>
</div>