src/Http/routes.php
<?php

Route::resource('roles', 'RolesController');
Route::resource('permissions', 'PermissionsController');
Route::resource('users.roles', 'UsersRolesController', ['only' => ['index', 'create', 'store']]);

Route::put('users/{user}/roles', ['as' => 'users.roles.update', 'uses' => 'UsersRolesController@update']);
Route::put('users/{user}/update-organization-roles', ['as' => 'users.roles.update-organization-roles', 'uses' => 'UsersRolesController@updateOrganizationRoles']);
Route::put('users/{user}/update-generic-roles', ['as' => 'users.roles.update-generic-roles', 'uses' => 'UsersRolesController@updateGenericRoles']);

src/Models/Role.php
<?php

namespace Klopal\Permissions\Models;

use Illuminate\Database\Eloquent\Model;
use Klopal\Permissions\Exceptions\RoleDoesNotExist;
use Klopal\Permissions\Models\Traits\HasPermissions;
use Klopal\Permissions\Contracts\Role as RoleContract;
use Klopal\Permissions\Models\Traits\RefreshesPermissionCache;

class Role extends Model implements RoleContract
{
    use HasPermissions;

    // When ever permission is stored, updated, deleted we flush related cache.
    use RefreshesPermissionCache;

    /**
     * @var array
     */
    public $fillable = ['name', 'slug', 'description', 'generic'];

    /**
     * Create a new Eloquent model instance.
     *
     * @param array $attributes
     */
    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);

        $this->setTable(config('klopal-permissions.table_names.roles'));
    }

    /**
     * A role may be assigned to various users.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function users()
    {
        return $this->belongsToMany(
            config('auth.model') ?: config('auth.providers.users.model'),
            config('klopal-permissions.table_names.user_role')
        )->withTimestamps();
    }

    /**
     * A role may be given various permissions.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function permissions()
    {
        return $this->belongsToMany(
            config('klopal-permissions.models.permission'),
            config('klopal-permissions.table_names.permission_role')
        )->withTimestamps();
    }

    /**
     * Find a role by its name.
     *
     * @param string $name
     *
     * @return Role
     *
     * @throws RoleDoesNotExist
     */
    public static function findByName($name)
    {
        $role = static::where('name', $name)->first();

        if (!$role) {
            throw new RoleDoesNotExist($name);
        }

        return $role;
    }
}

src/Http/Controllers/Traits/Roles.php
<?php

namespace Klopal\Permissions\Http\Controllers\Traits;

use Illuminate\Http\Request;
use Illuminate\Routing\Router;
use Klopal\Permissions\Contracts\Role;
use Klopal\Permissions\Contracts\Permission;
use Klopal\Permissions\Routes;

trait Roles
{
    /**
     * @param Request $request
     * @param Router $router
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(Request $request, Router $router)
    {
        abort_unless($request->user()->can($router->currentRouteName()), 403);

        $roles = app(Role::class)->all();

        return view('permissions::roles.index', compact('roles'));
    }

    /**
     * @param Request $request
     * @param Router $router
     * @param Routes $routes
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create(Request $request, Router $router, Routes $routes)
    {
        abort_unless($request->user()->can($router->currentRouteName()), 403);

        $permissions = app(Permission::class)->all();

        $routes = $routes->virtualPermissionRoutes($permissions);

        $role = app(Role::class);

        return view('permissions::roles.create', compact('permissions', 'routes', 'role'));
    }

    /**
     * @param Request $request
     * @param Router $router
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request, Router $router)
    {
        abort_unless($request->user()->can($router->currentRouteName()), 403);

        $this->validate($request, [
            'name' => 'required|max:255|unique:roles,name',
            'slug' => 'required|max:255|unique:roles,slug',
        ]);

        $role = app(Role::class)->create($request->all());

        $role->syncPermissions($request->get('permissions', []));

        return redirect()->route('roles.index');
    }

    /**
     * @param Request $request
     * @param Router $router
     * @param $role
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show(Request $request, Router $router, $role)
    {
        abort_unless($request->user()->can($router->currentRouteName()), 403);

        $role = app(Role::class)->findOrFail($role);

        return view('permissions::roles.show', compact('role'));
    }

    /**
     * @param Request $request
     * @param Router $router
     * @param $role
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(Request $request, Router $router, Routes $routes, $role)
    {
        abort_unless($request->user()->can($router->currentRouteName()), 403);

        $role = app(Role::class)->findOrFail($role);

        $permissions = app(Permission::class)->all();

        $routes = $routes->virtualPermissionRoutes($permissions);

        return view('permissions::roles.edit', compact('role', 'permissions', 'routes'));
    }

    /**
     * @param Request $request
     * @param Router $router
     * @param $role
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, Router $router, $role)
    {
        abort_unless($request->user()->can($router->currentRouteName()), 403);

        $role = app(Role::class)->findOrFail($role);

        $this->validate($request, [
            'name' => 'required|max:255|unique:roles,name,' . $role->id,
            'slug' => 'required|max:255|unique:roles,slug,' . $role->id,
        ]);

        $role->update($request->all());

        $role->syncPermissions($request->get('permissions', []));

        return redirect()->route('roles.index');
    }

    /**
     * @param Request $request
     * @param Router $router
     * @param $role
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(Request $request, Router $router, $role)
    {
        abort_unless($request->user()->can($router->currentRouteName()), 403);

        $role = app(Role::class)->findOrFail($role);

        $relatedUsers = $role->users;

        // Do not delete role if there is users connected. Maybe allow it later..
        if (empty($relatedUsers)) {
            $role->delete();
        }

        return redirect()->route('roles.index');
    }
}

src/resources/views/roles/partials/form.blade.php
<form method="POST" action="{{ $role->exists ? route('roles.update', $role) : route('roles.store') }}"
      accept-charset="UTF-8">
    @if($role->exists)<input name="_method" type="hidden" value="PUT">@endif
    <input name="_token" type="hidden" value="{{ csrf_token() }}">

    <div class="row">
        <div class="col-sm-6">
            <div class="form-group{{ $errors->first('name', ' has-error') }}">
                <label for="name" class="control-label">@lang('permissions::roles.name')</label>
                <input class="form-control" name="name" type="text" id="name" value="{{ old('name', $role->name) }}">
                <span class="help-block">{{ $errors->first('name', ':message') }}</span>
                @if(!$errors->first('name'))<span class="help-block"></span>@endif
            </div>
        </div>
        <div class="col-sm-6">
            <div class="form-group{{ $errors->first('slug', ' has-error') }}">
                <label for="slug" class="control-label">@lang('permissions::roles.slug')</label>
                <input class="form-control" name="slug" type="text" id="slug" value="{{ old('slug', $role->slug) }}">
                <span class="help-block">{{ $errors->first('slug', ':message') }}</span>
                @if(!$errors->first('slug'))<span class="help-block">@lang('permissions::roles.slug_help')</span>@endif
            </div>
        </div>
    </div>

    <div class="form-group{{ $errors->first('description', ' has-error') }}">
        <label for="description" class="control-label">@lang('permissions::roles.description')</label>
        <textarea class="form-control" name="description" cols="50" rows="5"
                  id="description">{{ old('description', $role->description) }}</textarea>
        <span class="help-block">{{ $errors->first('description', ':message') }}</span>
    </div>

        <div class="form-group{{ $errors->first('generic', ' has-error') }}">
            <label for="description" class="control-label">@lang('permissions::roles.generic')</label>

            <input name="generic" type="hidden" value="0">

            <div class="checkbox">
                <label>
                    <input type="checkbox" name="generic" value="0"> @lang('permissions::roles.generic')
                </label>
            </div>

            <span class="help-block">{{ $errors->first('generic', ':message') }}</span>
        </div>

    <hr/>

    <label>@lang('permissions.permissions')</label>

    <table class="table table-hover table-condensed">
        <thead>
        <tr>
            <th class="col-sm-1"></th>
            <th class="col-sm-3">{{ trans('permissions::roles.name') }}</th>
            <th class="col-sm-7">{{ trans('permissions::roles.description') }}</th>
            <th class="text-right col-sm-1"></th>
        </tr>
        </thead>
        <tbody>
        @foreach ($permissions as $key => $permission)
            <tr>
                <td>
                    <input type="checkbox" id="p{{ $key }}" name="permissions[{{ $key }}]"
                           value="{{ $permission->name }}"
                    @if(!empty(old('permissions')))
                        {{ in_array($permission->name, old('permissions')) ? 'checked ' : '' }}
                            @else
                        {{ ($role->exists && $role->permissions->contains($permission)) ? 'checked' : '' }}
                            @endif
                    />
                </td>
                <td>
                    <label for="p{{ $key }}" style="display:block">
                        {{ $permission->name }}
                    </label>
                </td>
                <td>{{ $permission->description }}</td>
                <td class="text-right"></td>
            </tr>
        @endforeach

        @foreach ($routes as $key => $route)
            <tr>
                <td>
                    <input type="checkbox" id="r{{ $key }}" name="permissions[]" value="{{ $route }}"
                    @if(!empty(old('permissions')))
                        {{ in_array($route, old('permissions')) ? 'checked ' : '' }}
                            @endif
                    />
                </td>
                <td>
                    <label class="text-muted" for="r{{ $key }}" style="display:block">
                        {{ $route }}
                    </label>
                </td>
                <td></td>
                <td class="text-right">
                    <span class="label label-default">Vitual</span>
                </td>
            </tr>
        @endforeach

        </tbody>
    </table>

    <hr/>

    <button class="btn btn-w-m btn-primary" type="submit">
        <i class="fa fa-fw fa-check"></i> @lang('permissions::roles.save')
    </button>
</form>

@if($role->exists)
    <form method="POST" action="{{ route('roles.destroy', $role) }}" accept-charset="UTF-8">
        <input name="_method" type="hidden" value="DELETE">
        <input name="_token" type="hidden" value="{{ csrf_token() }}">

        <button class="btn btn-w-m btn-danger" type="submit">
            <i class="fa fa-fw fa-trash"></i> @lang('permissions::roles.delete')
        </button>
    </form>
@endif

src/resources/views/roles/partials/list.blade.php
<table class="table table-hover">
    <thead>
    <tr>
        <th class="narrow">#</th>
        <th>{{ trans('permissions::roles.name') }}</th>
        <th>{{ trans('permissions::roles.slug') }}</th>
        <th>{{ trans('permissions::roles.description') }}</th>
        <th class="text-right"></th>
    </tr>
    </thead>
    <tbody>
    @foreach ($roles as $role)
        <tr>
            <td>{{ $role->id }}</td>
            <td>{{ $role->name }}</td>
            <td>{{ $role->slug }}</td>
            <td>{{ $role->description }}</td>

            <td class="narrow text-nowrap text-right">

                <form method="post" action="{{ route('roles.destroy', $role) }}">

                    <a class="btn btn-sm btn-default"
                       href="{{ route('roles.show', $role) }}">
                        <i class="fa fa-search" aria-hidden="true"></i>
                    </a>

                    <a class="btn btn-sm btn-default"
                       href="{{ route('roles.edit', $role) }}">
                        <i class="fa fa-pencil" aria-hidden="true"></i>
                    </a>

                    <!-- CSRF Token -->
                    {!! csrf_field() !!}

                    {!! method_field('delete') !!}

                    <button class="btn btn-sm btn-danger btn-outline">
                        <i class="fa fa-trash" aria-hidden="true"></i>
                    </button>
                </form>
            </td>
        </tr>
    @endforeach
    </tbody>
</table>

src/resources/views/roles/partials/show.blade.php
<div class="row">
    <div class="col-sm-4 col-md-2">
        @lang('permissions::roles.name')
    </div>
    <div class="col-sm-8 col-md-10">
        {{ $role->name }}
    </div>
</div>

@hr

<div class="row">
    <div class="col-sm-4 col-md-2">
        @lang('permissions::roles.slug')
    </div>
    <div class="col-sm-8 col-md-10">
        {{ $role->slug }}
    </div>
</div>

@hr

<div class="row">
    <div class="col-sm-4 col-md-2">
        @lang('permissions::roles.description')
    </div>
    <div class="col-sm-8 col-md-10">
        {{ $role->description }}
    </div>
</div>

@hr

<div class="row">
    <div class="col-sm-4 col-md-2">
        @lang('permissions::permissions.permissions')
    </div>
    <div class="col-sm-8 col-md-10">

        @forelse($role->permissions as $permission)
            {{ $permission->name }}@if($loop->remaining), @endif
        @empty

        @endforelse
    </div>
</div>

@hr

<div class="row">
    <div class="col-sm-4 col-md-2">
        @lang('permissions::roles.created_at')
    </div>
    <div class="col-sm-8 col-md-10">
        {{ $role->created_at }}
    </div>
</div>

@hr

<div class="row">
    <div class="col-sm-4 col-md-2">
        @lang('permissions::roles.updated_at')
    </div>
    <div class="col-sm-8 col-md-10">
        {{ $role->updated_at }}
    </div>
</div>